config/routes.rb
Rails.application.routes.draw do

  resources :events do
    match '/scrape', to: 'events#scrape', via: :post, on: :collection
  end
  root to: 'events#index'
  post 'scrape_event', to: 'events#scrape_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    # binding.pry
    if params[:search]
      @parameter = params[:search].downcase
      @events = Event.all.where("lower(title) LIKE :search", search: "%#{@parameter}%").paginate(page: params[:page], per_page: 21)
    else
      @events = Event.paginate(page: params[:page], per_page: 21)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @events = Event.new(events_params)
    if @events.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def scrape_event
    if params[:url].include?('visitberlin')
      response = VisitBerlinService.process(params[:url])
    else
      response = GorkiService.process(params[:url])
    end
    redirect_to root_path
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  private
    def events_params
      params.require(:event).permit(:title, :date, :place, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
	<%= f.input :title, lable: "Event Title", class: "form-control" %>
	<%= f.input :date , class: "form-control"%>
	<%= f.input :place, class: "form-control" %>
	<%= f.input :description, class: "form-control" %>
	<%= f.button :submit, class: "btn-custom2" %>
<% end %>

app/views/events/index.html.erb
<div class="row">
<%= form_tag('/scrape_event') do %>
	Enter events url: <input type="text" name="url" value="">
	<input type="submit" name="submit">
<% end %>

<% if @events.count == 0 %>
	<h2>There are no Events to show, Please enter event url to scrape ("https://www.visitberlin.de/en/event-calendar-berlin") :)</h2>
<% else %>

<%= form_tag(events_path, method: 'get') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search event with title", class: "form-control"%>
    <div class="input-group-btn">
      <%= button_tag "Search for Events", class: 'btn btn-info glyphicon-search', name: nil%>
    </div>
  </div>
<% end %>

<div class="container">
<%= will_paginate @events, renderer: BootstrapPagination::Rails%>
 <table class="table">
  <thead class="thead-dark">
    <tr> 
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Place</th>
      <th scope="col">Description</th>
    </tr>
  </thead><%#= will_paginate @events %> 
  <% @events.each do |event| %>
  <tbody>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.date %></td>
      <td><%= event.place %></td>
      <td><%= event.description[0..50]%></td>
    </tr>
    <% end %>
  </tbody>

  <% end %> 
</table>

<%= will_paginate @events, renderer: BootstrapPagination::Rails%>  
<h2><%= link_to 'Add Event', new_event_path %></h2></br>
<%= link_to 'Back', events_path %>
</div>


</div>

app/views/events/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-event-form">
    <h1>New Event</h1>
    <%= render 'form' %>
  </div>
  <%= link_to 'Back', events_path %>
</div>

app/views/events/search.html.erb
<div class="row">
<%= form_tag('/scrape_event') do %>
	Enter events url: <input type="text" name="url" value="">
	<input type="submit" name="submit">
<% end %>

<% if @events.count == 0 %>
	<h1>There are no Events to show, Please add a event :)</h1>
<% else %>

<div class="col-md-6 col-md-offset-3">
<%= form_tag(events_path, method: 'get') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control"%>
    <div class="input-group-btn">
      <%= button_tag "Search for Events", class: 'btn btn-info glyphicon-search', name: nil%>
    </div>
  </div>
<% end %>
</div>

<div class="container">
<%= will_paginate @events, renderer: BootstrapPagination::Rails%>
 <table class="table">
  <thead class="thead-dark">
    <tr> 
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Place</th>
      <th scope="col">Description</th>
    </tr>
  </thead><%#= will_paginate @events %> 
  <% @events.each do |event| %>
  <tbody>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.date %></td>
      <td><%= event.place %></td>
      <td><%= event.description[0..50]%></td>
    </tr>
    <% end %>
  </tbody>

  <% end %> 
</table>

<%= will_paginate @events, renderer: BootstrapPagination::Rails%>  
</div>

<%= link_to 'Add Event', new_event_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CulturalActivitiesInfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>